### ISSUE TITLE
PHP 8.0 Support 

### ISSUE THREAD

**Issue by MathiasGmeiner** [amteich/kirby-twig#15]
I'm not sure but I think for supporting PHP 8 Twig should be at least at `2.13.0`

**Comment by ceesvanegmond** [comment]
👍  We also need to remove these mentions
![—](https://user-images.githubusercontent.com/883497/102781584-30ef2100-4398-11eb-8f5d-40b5a2046f88.png)

**Comment by seehat** [comment]
Thank you for your help regarding PHP 8. 

This should be fixed in the new release 3.0.2, where I updated to Twig 3.

**Comment by MathiasGmeiner** [comment]
It's working fine with the new release! Thanks for that!
