### ISSUE TITLE
References to old repository name (mgfagency/kirby-twig)

### ISSUE THREAD

**Issue by fvsch** [amteich/kirby-twig#16]
I found a couple  references to the old repository:

1. In `README.md`:

```
git submodule add https://github.com/mgfagency/kirby-twig.git site/plugins/kirby-twig
```

2. Links on https://getkirby.com/plugins/mgfagency/twig

GitHub does redirect to this repository and the `git submodule` command still works, but maybe these could be changed.

I’d also recommend adding the list of maintainers for this plugin in the “Credits” section of the README.

**Comment by seehat** [comment]
Yes. It was time to change this. Thanks for the hint.
