### ISSUE TITLE
Composer install yields InvalidArgumentException

### ISSUE THREAD

**Issue by renestalder** [amteich/kirby-twig#18]
Trying to install via composer as written in the readme yields following error:
```
[InvalidArgumentException]                                                                                                                                                                                  
  Could not find a matching version of package amteich/kirby-twig. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-stability  
   (stable).  

```

Is it possbile you changed the project path/namespace on GitHub and that the old one was [mgfagency/kirby-twig ](https://packagist.org/packages/mgfagency/kirby-twig), which is still used in the composer repository?

**Comment by seehat** [comment]
Sry for the inconvenience. I moved the composer package to https://packagist.org/packages/amteich/kirby-twig

Now it should work. I testet it a few seconds ago.
