### ISSUE TITLE
How to use Kirby collections in a twig template

### ISSUE THREAD

**Issue by sonicpunk** [amteich/kirby-twig#19]
Could I see an example of how to use collections in twig?

https://getkirby.com/docs/guide/templates/collections

Thanks!

**Comment by seehat** [comment]
Of course, you can use the kirby helper function `collection()`: https://getkirby.com/docs/reference/templates/helpers/collection

Example if you have a collection named `newsentries`:
```
{% for item in collection('newsentries') %}
  {{ item.title }}
{% endfor %}
```

**Comment by sonicpunk** [comment]
Thanks for this!

**Comment by seehat** [comment]
You're welcome.
