### ISSUE TITLE
Not compatible with kirby layouts extension

### ISSUE THREAD

**Issue by tobystokes** [amteich/kirby-twig#32]
Firstly, thanks for this excellent plugin, it works great!

Except just to note that it seems to be incompatible with the [kirby layouts](https://github.com/getkirby/layouts) plugin.

Now obviously, you won't need `<?php layout() ?>` if you now have `{% extends 'layout.twig' %}` - but this caught me out when I was in the process of converting templates, you will need to uninstall/remove the layouts plugin before adding twig.

**Comment by seehat** [comment]
Yes, I think that both won't work at the same time, as they use the same php mechanics to prepare templates and output.

**Comment by seehat** [comment]
> Firstly, thanks for this excellent plugin, it works great!

You are welcome. :)
