### ISSUE TITLE
Register new templates?

### ISSUE THREAD

**Issue by tobystokes** [amteich/kirby-twig#33]
(While I have your attention!) Is it possible to register new twig templates in a plugin?
Previously, I has something like

```
Kirby::plugin('your/plugin', [
    'templates' => [
        'blog' => __DIR__ . '/templates/blog.php'
    ]
]);
```
But pointing directly to a `.twig` file doesn't seem to work.
I have a feeling it is possible by returning a `new amteich\Twig\Template(...)` perhaps?, but can't work it out...

**Comment by seehat** [comment]
Hmm, this should work. I have a Test-Installation and use following code, which is loading the template:

```php
Kirby::plugin('site/blog', [
  'templates' => [
    'home' => __DIR__ . '/templates/home.twig'
  ]
]);
```

**Comment by tobystokes** [comment]
Doh, because I was after a template in the main templates folder, not the plug-in.

`'home' => kirby()->root('templates') . '/home.twig'` <- is what I was after, and yes it works! Thanks.
